[package]
name = "cman"
version = "0.1.0"
edition = "2024"
description = "A Cargo-like build tool for C"
license = "MIT"
readme = "README.md"
repository = "https://github.com/TechieQuokka/cbuild"
homepage = "https://github.com/TechieQuokka/cbuild"
documentation = "https://github.com/TechieQuokka/cbuild"
keywords = ["c", "build", "build-system", "make", "cargo"]
categories = ["development-tools::build-utils", "command-line-utilities"]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
